export const usernameErrors = {
    USERNAME_EMPTY: 'USERNAME_EMPTY',
    USERNAME_NOT_ALPHANUMERIC: 'USERNAME_NOT_ALPHANUMERIC',
};

export const emailErrors = {
    EMAIL_EMPTY: 'EMAIL_EMPTY',
    EMAIL_INVALID: 'EMAIL_INVALID',
};

export const passwordErrors = {
    PASSWORD_EMPTY: 'PASSWORD_EMPTY',
    PASSWORD_INVALID: 'PASSWORD_INVALID',
};

export const confirmPasswordErrors = {
    CONFIRM_PASSWORD_EMPTY: 'CONFIRM_PASSWORD_EMPTY',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
};
